const STORE_CONFIG_MOCK_RESP = {
  storeConfig: {
    allow_guests_to_write_product_reviews: '1',
    allow_items: null,
    allow_order: null,
    base_currency_code: 'USD',
    catalog_default_sort_by: 'position',
    category_fixed_product_tax_display_setting: 'FPT_DISABLED',
    cms_home_page: 'home',
    cms_no_cookies: 'enable-cookies',
    cms_no_route: 'no-route',
    configurable_thumbnail_source: 'parent',
    copyright: 'Copyright © 2013-present Magento, Inc. All rights reserved.',
    default_description: null,
    default_display_currency_code: 'USD',
    default_keywords: null,
    default_title: 'Magento Commerce',
    grid_per_page: 12,
    grid_per_page_values: '12,24,36',
    head_shortcut_icon: null,
    header_logo_src: null,
    is_default_store: true,
    is_default_store_group: true,
    list_mode: 'grid-list',
    list_per_page: 10,
    list_per_page_values: '5,10,15,20,25',
    locale: 'en_US',
    logo_alt: null,
    logo_height: null,
    logo_width: null,
    magento_wishlist_general_is_enabled: '1',
    minimum_password_length: '8',
    no_route: 'cms/noroute/index',
    product_fixed_product_tax_display_setting: 'FPT_DISABLED',
    product_reviews_enabled: '1',
    required_character_classes_number: '3',
    root_category_uid: 'Mg==',
    sales_fixed_product_tax_display_setting: 'FPT_DISABLED',
    store_code: 'default',
    store_group_code: 'main_website_store',
    store_group_name: 'Main Website Store',
    store_name: 'Default Store View',
    store_sort_order: 0,
    timezone: 'America/Chicago',
    title_prefix: null,
    title_separator: '-',
    title_suffix: null,
    use_store_in_url: false,
    website_code: 'base',
    website_name: 'Main Website',
    weight_unit: 'lbs',
    welcome: 'Default welcome msg!',
  },
};

export {
  STORE_CONFIG_MOCK_RESP,
};
