name: Bug report
description: Create a report to help us improve
title: '[Bug]: '
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and how it happened.
      placeholder: Current Behavior
      value: ""
    validations:
      required: true
  - type: textarea
      id: what-to-expect
      attributes:
        label: What was supposed to be expected?
        description: Can you tell us, what was supposed to be expected?
        placeholder: Expected Behavior
        value: ""
      validations:
        required: false
  - type: textarea
      id: solution
      attributes:
        label: Do you have any possible solution or fix for this bug?
        description: Also, if possible provide the information on how to implement the solution.
        placeholder: Possible Solution
        value: ""
      validations:
        required: false
  - type: textarea
      id: reproduce
      attributes:
        label: How we can reproduce this bug?
        description: Please provide detailed instructions on how to reproduce.
        placeholder: Steps to Reproduce
        value: ""
      validations:
        required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the Magento 2integration you are using?
      options:
        - 1.0.0-beta.14
        - 1.0.0-beta.10
        - 1.0.0-beta.9
        - 1.0.0-beta.8
        - 1.0.0-beta.7
        - 1.0.0-beta.6
        - 1.0.0-beta.5
        - 1.0.0-beta.4
        - 1.0.0-beta.3
        - 1.0.0-beta.2
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: node
    attributes:
      label: What node version you were using?
      multiple: false
      options:
        - 16.x
        - 15.x
        - 14.x
        - 13.x
        - 12.x
        - 11.x
        - 10.x
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/vuestorefront/magento2/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
