name: PR to Author
on:
  pull_request:
    types: [opened, ready_for_review, edited, synchronize]

jobs:
  assignAuthor:
    name: Assing
    runs-on: ubuntu-latest
    steps:
      - uses: samspills/assign-pr-to-author@v1.0
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
