name: Commitlint PR Title
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    name: Validate PR Title (conventional-commit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Dependencies
        run: yarn

      - uses: JulienKode/pull-request-name-linter-action@v0.2.0
