 # https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
on:
  workflow_call:
    inputs:
      environment-code:
        required: true
        type: string

    secrets:
       cloud-username:
         required: true
       cloud-password:
         required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if curl -s -H 'X-User-Id: ${{ secrets.cloud-username }}'  -H 'X-Api-Key: ${{ secrets.cloud-password }}' -H 'Content-Type: application/json' -X POST -d '{
              "code":"${{ inputs.environment-code }}",
              "region":"europe-west1.gcp",
              "frontContainerVersion":"${{ github.sha }}"
            }' https://farmer.storefrontcloud.io/instances | grep -q '{"code":200,"result":"Instance updated!"}'; then
            echo "Instance updated"
          else
            echo "Something went wrong during the update process..."
            exit 1
          fi

        # the above curl only *asks* for the container to be deployed
        # we don't know when the newly built Docker image replaces the old one
        # but it takes less than 5 minutes
      - name: 'Wait for container deployed on VSF Cloud to come online'
        run: 'sleep 300'
        shell: 'bash'
