name: "Run SpeedCurve test"

on:
  deployment_status:

jobs:
  speedcurve:
    if: github.deployment.ref == 'refs/heads/develop' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: 'Wait for container deployed on VSF Cloud to come online'
        run: 'sleep 300'
        shell: 'bash'

      - name: 'Ask SpeedCurve to run performance tests'
        uses: SpeedCurve-Metrics/speedcurve-test-action@v1.2.1
        with:
          api_key: ${{ secrets.SPEEDCURVE_API_KEY }}
          site_id: 744017
          note: commit ${{ github.deployment.sha }} from deployment ${{ github.deployment.url }}
